### PR TITLE
Switch from logging framework Log4J2 to logging facade SLF4J

### PR DESCRIPTION
**Pull request by valfirst**
## Description
`saucerest-java` is a client for SauceLabs API (library). In other words it can't be used as a standalone application, it's used as dependency for other libraries and applications. That's why `saucerest-java` shouldn't have tight coupling with any logging framework and shouldn't have any hardcoded logging configuration (which may bring collisions to users).

## Motivation and Context
The problem was introduced in this commit: https://github.com/saucelabs/saucerest-java/commit/a989460ab904b06ac1b9b8dcbbed1081ba5a7192.
`saucerest-java` should:
- rely on logging facade (SLF4J) instead of particular logging framework
- declare logging configuration only for testing purposes.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (change which improves current code base; please describe the change)
- [?] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/saucelabs/saucerest-java/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All new and existing tests passed locally
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by diemol — COMMENTED** [review]
Why don't we remove it completely?

**Comment by valfirst** [comment]
> Why don't we remove it completely?

Not sure what "it" means here. If the question is about Log4J2, it was moved to be used in unit tests only. If it's needed, I can remove Log4J completely and use some simple provider like [`slf4j-nop` or `slf4j-simple`](https://www.slf4j.org/manual.html#swapping)

**Comment by diemol** [comment]
> > Why don't we remove it completely?
> 
> Not sure what "it" means here. If the question is about Log4J2, it was moved to be used in unit tests only. If it's needed, I can remove Log4J completely and use some simple provider like [`slf4j-nop` or `slf4j-simple`](https://www.slf4j.org/manual.html#swapping)

Yes, that is what I meant. Removing Log4J2 completely.

**Review by diemol — APPROVED** [review]
Thank you, @valfirst!

**Pull request merged**
