### PR TITLE
Migrate from Moshi/org.json to Gson

### PR DESCRIPTION
**Pull request by diemol**
## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (change which improves current code base; please describe the change)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/saucelabs/saucerest-java/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All new and existing tests passed locally
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by diemol** [comment]
@valfirst seems CI is failing. Could you please check?

**Comment by valfirst** [comment]
@diemol I've added a new commit to my branch from fork: https://github.com/valfirst/saucerest-java/commit/54602e218fedde5961e51cf82b7e9b0981bb4a5e (I hope it will fix all issues in integration tests, I don't have SL account with permissions enough to test all endpoints)

**Comment by diemol** [comment]
Can you please create a PR to this [branch](https://github.com/saucelabs/saucerest-java/tree/pr_530) so I can merge it to rerun the CI?

**Comment by valfirst** [comment]
Done: https://github.com/saucelabs/saucerest-java/pull/534

**Comment by diemol** [comment]
Thank you, @valfirst!

**Pull request merged**
