### PR TITLE
adding proxy if available to open a connection

### PR DESCRIPTION
**Pull request by vickiSlobodeniuk**

### CODE REVIEW

**Comment by yfangsl** [comment]
This seems ok, but would it be possible to add some tests for the new proxy settings?

**Comment by vickiSlobodeniuk** [comment]
Hi @yfangsl,

It's a bit difficult to test as URL is a final class. Would it be ok if add https://github.com/powermock/powermock library for testing?

**Comment by yfangsl** [comment]
Yeah, go ahead.

**Comment by vickiSlobodeniuk** [comment]
@yfangsl unfortunately we don't have time capacity to add tests to this change. it will have to go without them.

**Pull request merged**
